"""
Module: Main Pipeline
---------------------
Role: Orchestrate the entire flow (Load -> Clean -> Validate -> Train -> Evaluate).
Usage: python src/main.py
"""
"""
Educational Goal:
- Why this module exists in an MLOps system: Provide a single, readable entrypoint that orchestrates the end-to-end pipeline.
- Responsibility (separation of concerns): Glue code only—calls load/clean/validate/features/train/evaluate/infer and materializes artifacts.
- Pipeline contract (inputs and outputs): Input is repository-local config + raw data; outputs are clean CSV, model artifact, and predictions CSV.

TODO: Replace print statements with standard library logging in a later session
TODO: Any temporary or hardcoded variable or parameter will be imported from config.yml in a later session
"""

from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split

from src.clean_data import clean_dataframe
from src.evaluate import evaluate_model
from src.features import get_feature_preprocessor
from src.infer import run_inference
from src.load_data import load_raw_data
from src.utils import save_csv, save_model
from src.validate import validate_dataframe


# =============================================================================
# CONFIGURATION (SETTINGS DICT BRIDGE)
# =============================================================================
# LOUD REMINDER:
# This SETTINGS dictionary is pre-configured to match the DUMMY CSV generated by src/load_data.py.
# Students MUST map these settings to their real dataset (paths, target column, feature lists, problem type).
SETTINGS = {
    "is_example_config": True,
    "paths": {
        "raw_data": "data/raw/sample.csv",
        "processed_clean": "data/processed/clean.csv",
        "model": "models/model.joblib",
        "predictions": "reports/predictions.csv",
    },
    "target_column": "target",
    "problem_type": "regression",  # "regression" or "classification"
    "test_size": 0.33,
    "random_state": 42,
    "features": {
        "quantile_bin": [],  # apply KBinsDiscretizer to numeric columns
        "categorical_onehot": ["cat_feature"],
        "numeric_passthrough": ["num_feature"],
        "n_bins": 3,
    },
}


def main():
    """
    Inputs:
    - None (configuration is defined in SETTINGS dict for scaffolding).
    Outputs:
    - None (materializes artifacts + prints metrics).
    Why this contract matters for reliable ML delivery:
    - A single, standard entrypoint enables automation (CI, scheduled runs) and makes the pipeline auditable.
    """
    print("[main.main] Starting end-to-end pipeline")  # TODO: replace with logging later

    # -------------------------------------------------------------------------
    # Step 0: Ensure artifact directories exist (manual materialization)
    # -------------------------------------------------------------------------
    print("[main.main] Ensuring required directories exist")  # TODO: replace with logging later
    Path("data/raw").mkdir(parents=True, exist_ok=True)
    Path("data/processed").mkdir(parents=True, exist_ok=True)
    Path("models").mkdir(parents=True, exist_ok=True)
    Path("reports").mkdir(parents=True, exist_ok=True)

    # -------------------------------------------------------------------------
    # Step 1: Example config guardrail
    # -------------------------------------------------------------------------
    print("[main.main] Checking SETTINGS for example configuration")  # TODO: replace with logging later
    if SETTINGS.get("is_example_config", False):
        print(
            "\n" + "=" * 80 + "\n"
            "[EXAMPLE CONFIG ENABLED] This run uses scaffolding settings.\n"
            "Replace SETTINGS with real dataset configuration for real projects.\n"
            + "=" * 80 + "\n"
        )  # TODO: replace with logging later

    # --------------------------------------------------------
    # START STUDENT CODE
    # --------------------------------------------------------
    # TODO_STUDENT: Replace SETTINGS with config.yml loading once introduced
    # Why: Central config reduces copy/paste drift and supports environment-specific parameters
    # Examples:
    # 1. Load YAML into SETTINGS at runtime
    # 2. Add CLI args for overriding paths
    #
    # Optional forcing function (leave commented)
    # raise NotImplementedError("Student: You must implement this logic to proceed!")
    #
    # Placeholder (Remove this after implementing your code):
    print("Warning: Student has not implemented this section yet")
    # --------------------------------------------------------
    # END STUDENT CODE
    # --------------------------------------------------------

    # -------------------------------------------------------------------------
    # Step 2: Load raw data
    # -------------------------------------------------------------------------
    print("[main.main] Loading raw data")  # TODO: replace with logging later
    raw_path = Path(SETTINGS["paths"]["raw_data"])
    df_raw = load_raw_data(raw_path)

    # -------------------------------------------------------------------------
    # Step 3: Clean data
    # -------------------------------------------------------------------------
    print("[main.main] Cleaning data")  # TODO: replace with logging later
    target_column = SETTINGS["target_column"]
    df_clean = clean_dataframe(df_raw, target_column=target_column)

    # -------------------------------------------------------------------------
    # Step 4: Save processed clean CSV
    # -------------------------------------------------------------------------
    print("[main.main] Saving cleaned dataset to data/processed/clean.csv")  # TODO: replace with logging later
    clean_path = Path(SETTINGS["paths"]["processed_clean"])
    save_csv(df_clean, clean_path)

    # -------------------------------------------------------------------------
    # Step 5: Validate
    # -------------------------------------------------------------------------
    print("[main.main] Validating cleaned dataset")  # TODO: replace with logging later
    required_cols = [target_column]
    required_cols += SETTINGS["features"]["quantile_bin"]
    required_cols += SETTINGS["features"]["categorical_onehot"]
    required_cols += SETTINGS["features"]["numeric_passthrough"]
    validate_dataframe(df_clean, required_columns=required_cols)

    # -------------------------------------------------------------------------
    # Step 6: Train/test split (done BEFORE any feature fitting to prevent leakage)
    # -------------------------------------------------------------------------
    print("[main.main] Creating train/test split (leakage prevention)")  # TODO: replace with logging later
    X = df_clean.drop(columns=[target_column])
    y = df_clean[target_column]

    stratify = y if SETTINGS["problem_type"] == "classification" else None
    try:
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=SETTINGS["test_size"],
            random_state=SETTINGS["random_state"],
            stratify=stratify,
        )
    except ValueError as e:
        print(
            f"[main.main] Stratified split failed ({e}). Falling back to non-stratified split."
        )  # TODO: replace with logging later
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=SETTINGS["test_size"],
            random_state=SETTINGS["random_state"],
            stratify=None,
        )

    # -------------------------------------------------------------------------
    # Step 7: Fail-fast feature checks (schema + numeric dtype for quantile binning)
    # -------------------------------------------------------------------------
    print("[main.main] Running fail-fast feature configuration checks")  # TODO: replace with logging later
    feature_cfg = SETTINGS["features"]

    configured_cols = (
        feature_cfg["quantile_bin"]
        + feature_cfg["categorical_onehot"]
        + feature_cfg["numeric_passthrough"]
    )

    missing_in_X = [c for c in configured_cols if c not in X_train.columns]
    if missing_in_X:
        raise ValueError(
            f"Feature config error: columns not found in X_train: {missing_in_X}. "
            f"Available: {list(X_train.columns)}"
        )

    # quantile-bin columns must be numeric dtypes
    for c in feature_cfg["quantile_bin"]:
        if not pd.api.types.is_numeric_dtype(X_train[c]):
            raise ValueError(
                f"Feature config error: quantile_bin column '{c}' must be numeric dtype, "
                f"but got dtype={X_train[c].dtype}"
            )

    # --------------------------------------------------------
    # START STUDENT CODE
    # --------------------------------------------------------
    # TODO_STUDENT: Add additional checks (high cardinality categories, leakage columns, timestamp splits)
    # Why: Preventing leakage and schema drift is a major source of business risk in ML delivery
    # Examples:
    # 1. Ensure no ID columns are accidentally used as features
    # 2. Enforce time-based splits for forecasting problems
    #
    # Optional forcing function (leave commented)
    # raise NotImplementedError("Student: You must implement this logic to proceed!")
    #
    # Placeholder (Remove this after implementing your code):
    print("Warning: Student has not implemented this section yet")
    # --------------------------------------------------------
    # END STUDENT CODE
    # --------------------------------------------------------

    # -------------------------------------------------------------------------
    # Step 8: Build feature recipe (unfitted ColumnTransformer)
    # -------------------------------------------------------------------------
    print("[main.main] Building feature preprocessor recipe")  # TODO: replace with logging later
    preprocessor = get_feature_preprocessor(
        quantile_bin_cols=feature_cfg["quantile_bin"],
        categorical_onehot_cols=feature_cfg["categorical_onehot"],
        numeric_passthrough_cols=feature_cfg["numeric_passthrough"],
        n_bins=feature_cfg["n_bins"],
    )

    # -------------------------------------------------------------------------
    # Step 9: Train model (Pipeline fits preprocessor ONLY on training split)
    # -------------------------------------------------------------------------
    print("[main.main] Training model")  # TODO: replace with logging later
    from src.train import train_model  # local import is fine; still absolute src path

    model = train_model(
        X_train=X_train,
        y_train=y_train,
        preprocessor=preprocessor,
        problem_type=SETTINGS["problem_type"],
    )

    # -------------------------------------------------------------------------
    # Step 10: Save model artifact
    # -------------------------------------------------------------------------
    print("[main.main] Saving trained model to models/model.joblib")  # TODO: replace with logging later
    model_path = Path(SETTINGS["paths"]["model"])
    save_model(model, model_path)

    # -------------------------------------------------------------------------
    # Step 11: Evaluate
    # -------------------------------------------------------------------------
    print("[main.main] Evaluating model on held-out test set")  # TODO: replace with logging later
    metric_value = evaluate_model(
        model=model,
        X_test=X_test,
        y_test=y_test,
        problem_type=SETTINGS["problem_type"],
    )

    if SETTINGS["problem_type"] == "regression":
        print(f"[main.main] Test RMSE: {metric_value:.6f}")  # TODO: replace with logging later
    else:
        print(f"[main.main] Test weighted F1: {metric_value:.6f}")  # TODO: replace with logging later

    # -------------------------------------------------------------------------
    # Step 12: Inference on example data (here: X_test) and save predictions
    # -------------------------------------------------------------------------
    print("[main.main] Running inference and saving predictions")  # TODO: replace with logging later
    df_pred = run_inference(model=model, X_infer=X_test)

    pred_path = Path(SETTINGS["paths"]["predictions"])
    save_csv(df_pred, pred_path)

    print("[main.main] Pipeline complete")  # TODO: replace with logging later


if __name__ == "__main__":
    main()